package org.smart.orm.execution;

import javax.sql.RowSet;
import java.sql.*;

public interface Executor {
    
    <T> void executeQuery(Connection connection, ResultHandler<T> handler, String sql, Object... args);
    
    RowSet executeQuery(Connection connection, String sql, Object... args);
    
    <T> int insert(Connection connection, ResultHandler<T> handler, String sql, int autoGeneratedKeys, Object... args);
    
    int update(Connection connection, String sql, Object... args);
    
    int delete(Connection connection, String sql, Object... args);
    
    <T> void execute(Connection connection, ResultHandler<T> handler, String sql);
    
}
