package org.smart.orm.execution;

import javax.sql.rowset.CachedRowSet;
import java.sql.*;

public interface Executor {
    
    <T> void executeQuery(Connection connection, String sql, ResultHandler<T> handler, Object... args);
    
    CachedRowSet executeQuery(Connection connection, String sql, Object... args);
    
    <T> int insert(Connection connection, String sql, ResultHandler<T> handler, int autoGeneratedKeys, Object... args);
    
    int update(Connection connection, String sql, Object... args);
    
    int delete(Connection connection, String sql, Object... args);
    
    <T> void execute(Connection connection, String sql, ResultHandler<T> handler);
    
}
